server:
  port: 8084
management:
  port: 3034
  context-path: /turbine
spring:
  mvc:
    throw-exception-if-no-handler-found: true
hystrix:
  command:
    default:
     execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
        timeout:
            enabled: false
custom:
  operation:
    server: ${operation.server}
