server:
  port: 8082
  context-path: /operation
spring:
  devtools:
    restart:
      additional-paths: applayer/operation/src/main/java
  mvc:
    throw-exception-if-no-handler-found: true
  thymeleaf:
    cache: false